<?php

namespace panix\mod\forsage;

use Yii;
use panix\engine\WebModule;
use yii\base\BootstrapInterface;

class Module extends WebModule implements BootstrapInterface
{
    public $apiKey = '';
    public $icon = '';
    public $unit = 1;
    public $type_id = 1;
    public $outStockDelete = true;
    public $onlySuppliers = [];

    public function bootstrap($app)
    {
        $app->urlManager->addRules(
            [
                'forsage/webhook' => 'forsage/default/webhook',
                'forsage/test' => 'forsage/default/test',
            ],
            true
        );
        /*$app->log->targets[] = [
            'class' => 'yii\log\FileTarget',
            'levels' => ['info'],
            'categories' => [
                'forsage'
            ],
            'logFile' => $app->runtimePath . '/logs/forsage.log',
        ];*/

    }

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getInfo()
    {
        return [
            'label' => Yii::t('seo/default', 'MODULE_NAME'),
            'author' => $this->author,
            'version' => '1.0',
            'icon' => $this->icon,
            'description' => Yii::t('seo/default', 'MODULE_DESC'),
            'url' => ['/admin/seo'],
        ];
    }


}
